```{r setup}
# Package names
packages <- c("jsonlite", "dplyr", "purrr")

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

# We have to create a desired data directory, if one does not yet exist
if (!dir.exists("data")) {
  dir.create("data")
} else {
  print("Output directory already exists")
}
```


```{r}
candidates <- c(
  "jaroslav_basta" = "102389958091735",
  "tomas_zima" = "236211929833146",
  "petr_pavel" = "102389958091735",
  "andrej_babis" = "214827221987263",
  "danuse_nerudova" = "102845669064210",
  "pavel_fischer" = "1934837773438430",
  "marek_hilser" = "280411075659709",
  "josef_stredula" = "1432139953751418",
  "denisa_rohanova" = "171740986593382"
)


# We have to create a desired directory, if one does not yet exist
if (!dir.exists("doc")) {
  dir.create("doc")
} else {
  print("Output directory already exists")
}

saveRDS(candidates, "doc/candidates.rds")
```

```{r}
# List all of the JSON data scraped from FB Ads library in the previous step
json_chunks <- list.files(path = "data/fb_report_spenders/", pattern = "top_spenders_\\S+\\.json", full.names = TRUE)

# Create a list of all of the subject we are interested in getting the political advertising info about.

remove_pages <-
  c(
    "European Parliament" = "178362315106",
    "European Commission" = "107898832590939",
    "World Food Programme" = "28312410177",
    "GoStudy" = "484856584931855",
    "AdVenture Communist" = "100451933698060",
    "UNICEF" = "68793499001",
    "Council of the European Union" = "147547541961576",
    "Azur Games" = "1238173096287495",
    "ROLEX" = "288607211258386"
  )


# Read all of the JSON data chunks in. 
pages_list <- json_chunks %>% 
  map(read_json) %>% 
  unlist(recursive = TRUE) %>%
  .[!. %in% remove_pages]

# Save the list to the .rds file
saveRDS(pages_list, "doc/saved_pages_list.rds")

# Delete the uneeded JSON chunks based on user input
if (readline(prompt = "Do you want to delete the JSON chunks (y/n) : ") == "y") {
  unlink(json_chunks)
  print("All JSON chunks deleted.")
} else {
  print("JSON chunks won't be deleted.")
}


```

